services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: chnawa-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chnawa
      - MONGO_INITDB_ROOT_PASSWORD=chnawa

volumes:
  mongodb_data:
